import type { Metadata } from 'next';
import Navbar from '@/components/Navbar';

export const metadata: Metadata = {
  title: 'Terms of Service — MangaTL',
};

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <main className="flex-1 max-w-2xl mx-auto w-full px-4 py-12 space-y-8">
        <div>
          <h1 className="text-3xl font-black text-gray-900">Terms of Service</h1>
          <p className="text-gray-400 text-sm mt-1">Last updated: April 2026</p>
        </div>

        <section className="space-y-3 text-gray-600 leading-relaxed">
          <h2 className="text-lg font-bold text-gray-900">Use of the service</h2>
          <p>
            MangaTL is a free web tool that uses AI image models to translate manga, manhwa,
            and manhua panels into English. By uploading a panel, you confirm that you have
            the right to do so and that the content does not violate copyright, trademark, or
            any applicable law. Do not upload panels you do not own or do not have permission
            to process.
          </p>
          <p>
            The service is provided &ldquo;as is,&rdquo; without warranties of any kind.
            Translations are generated by machine-learning models and may contain errors,
            omissions, or unintended text. Do not rely on the output for legal, medical,
            commercial, or safety-critical use.
          </p>
        </section>

        <section className="space-y-3 text-gray-600 leading-relaxed">
          <h2 className="text-lg font-bold text-gray-900">Daily limits and fair use</h2>
          <p>
            Each visitor gets a limited number of free uses per UTC day, enforced via a
            signed cookie (see the{' '}
            <a href="/privacy" className="text-accent-600 hover:underline">
              Privacy Policy
            </a>
            ). Automated abuse, scraping, or attempts to circumvent the rate limits are not
            allowed and may result in blocks.
          </p>
        </section>

        <section className="space-y-3 text-gray-600 leading-relaxed">
          <h2 className="text-lg font-bold text-gray-900">Intellectual property</h2>
          <p>
            You retain all rights to images you upload. We claim no ownership over your
            content or the translated output. Do not upload material you do not have the
            right to process.
          </p>
        </section>

        <section className="space-y-3 text-gray-600 leading-relaxed">
          <h2 className="text-lg font-bold text-gray-900">Limitation of liability</h2>
          <p>
            To the fullest extent permitted by law, MangaTL is not liable for any indirect,
            incidental, or consequential damages arising from use of the service, including
            but not limited to lost profits, data loss, or business interruption. Total
            liability for any claim is capped at the amount you have paid to use the service
            (which, for a free tool, is zero).
          </p>
        </section>

        <section className="space-y-3 text-gray-600 leading-relaxed">
          <h2 className="text-lg font-bold text-gray-900">Changes</h2>
          <p>
            We may update these terms from time to time. Continued use of the service after
            changes are posted constitutes acceptance of the updated terms.
          </p>
        </section>

        <section className="space-y-3 text-gray-600 leading-relaxed">
          <h2 className="text-lg font-bold text-gray-900">Contact</h2>
          <p>
            Questions or concerns? Email{' '}
            <a href="mailto:hello@mangatl.com" className="text-accent-600 hover:underline">
              hello@mangatl.com
            </a>
            .
          </p>
        </section>
      </main>
    </div>
  );
}
